-- Frases del día. Tono deliberado: acompañan, no arengan. Nada de "tú puedes
-- con todo" ni promesas de que será fácil — quien está dejando algo ya escuchó
-- eso mil veces y no le sirvió.

insert into public.quotes (text, author, tag) values
  ('No tienes que ganarle a la vida entera hoy. Solo a este día.', null, 'hoy'),
  ('Las ganas se van solas si les das veinte minutos.', null, 'craving'),
  ('Nadie deja nada de un solo golpe. Se deja un día a la vez, muchas veces.', null, 'proceso'),
  ('El impulso es una ola: sube, revienta y baja. No tienes que nadar, solo esperar.', null, 'craving'),
  ('Hoy no es para siempre. Hoy es hoy.', null, 'hoy'),
  ('La incomodidad de resistir dura menos que el arrepentimiento de ceder.', null, 'craving'),
  ('Estás cambiando algo que llevaba años en automático. Claro que cuesta.', null, 'proceso'),
  ('Contar los días también es una forma de cuidarte.', null, 'racha'),
  ('Que hoy sea difícil no significa que estés fallando.', null, 'dificil'),
  ('Un día limpio no se borra. Ya es tuyo.', null, 'racha'),
  ('El cuerpo tarda en creerte. Dale tiempo.', null, 'proceso'),
  ('Lo que hoy te pide el impulso, mañana no lo va a recordar.', null, 'craving'),
  ('No estás renunciando a algo. Estás recuperando algo.', null, 'sentido'),
  ('La constancia no es no fallar nunca. Es volver siempre.', null, 'recaida'),
  ('Si hoy solo pudiste aguantar, hoy hiciste suficiente.', null, 'dificil'),
  ('Cada vez que no cedes, la próxima vez pesa un poco menos.', null, 'craving'),
  ('Tu yo de mañana está esperando a ver qué haces hoy.', null, 'hoy'),
  ('Empezar de nuevo no borra lo que ya aprendiste.', null, 'recaida'),
  ('El aburrimiento también pasa. No hace falta llenarlo con eso.', null, 'craving'),
  ('Aguantar hoy no te hace especial. Te hace consistente.', null, 'racha'),
  ('Lo difícil no es decidirlo. Es sostenerlo un martes cualquiera.', null, 'proceso'),
  ('Nadie está mirando. Por eso cuenta más.', null, 'sentido'),
  ('El día que no tienes ganas es el día que más suma.', null, 'dificil'),
  ('Una recaída es un dato, no un veredicto.', null, 'recaida'),
  ('No te prometas nunca más. Prométete hoy no.', null, 'hoy'),
  ('La ansiedad de las primeras semanas no es señal de que va mal.', null, 'proceso'),
  ('Cambiar de hábito es cambiar de identidad, y eso incomoda.', null, 'sentido'),
  ('Hoy elegiste distinto. Eso ya cambia algo.', null, 'racha'),
  ('Si te caíste, lo urgente no es explicarlo. Es el día siguiente.', null, 'recaida'),
  ('Los primeros días son los más ruidosos. Después baja el volumen.', null, 'proceso'),
  ('No necesitas motivación. Necesitas que hoy termine.', null, 'dificil'),
  ('La parte de ti que quiere dejarlo también eres tú.', null, 'sentido'),
  ('Sumar un día no se siente a nada. Sumar treinta sí.', null, 'racha'),
  ('Descansa, come, duerme. Buena parte del impulso es cansancio disfrazado.', null, 'craving'),
  ('Contarle a alguien lo hace más difícil de esconder. Por eso funciona.', null, 'apoyo'),
  ('El deseo no es una orden.', null, 'craving'),
  ('Hoy vale por sí mismo, aunque mañana falles.', null, 'hoy'),
  ('Lo que estás haciendo no se ve por fuera todavía. Se está viendo por dentro.', null, 'proceso'),
  ('No busques sentirte bien. Busca terminar el día.', null, 'dificil'),
  ('Volver al día uno duele, pero el día uno ya lo sabes hacer.', null, 'recaida'),
  ('Una racha larga empieza igual que una corta.', null, 'racha'),
  ('El alivio que promete dura menos que lo que cobra.', null, 'craving'),
  ('Escribe qué sentiste hoy. Mañana te va a servir.', null, 'bitacora'),
  ('No te midas contra quien empezó hace un año.', null, 'sentido'),
  ('Estar incómodo y no ceder es exactamente el ejercicio.', null, 'craving'),
  ('Hay días que solo hay que atravesar. Hoy puede ser uno.', null, 'dificil'),
  ('Lo que repites te construye, aunque no lo notes.', null, 'proceso'),
  ('Perdiste un día, no el progreso.', null, 'recaida'),
  ('Marcar el día es un acto pequeño. Repetirlo no.', null, 'racha'),
  ('El impulso miente sobre cuánto va a durar.', null, 'craving'),
  ('No tienes que sentirte fuerte para actuar como si lo fueras.', null, 'dificil'),
  ('Lo dejaste hoy. Eso ya es un hecho, no una intención.', null, 'hoy'),
  ('Si el día se te complicó, cambia el plan, no la meta.', null, 'proceso'),
  ('Pedir ayuda no es recaer. Muchas veces es lo contrario.', null, 'apoyo'),
  ('La vergüenza empuja a repetir. La honestidad, no.', null, 'recaida'),
  ('Vas a querer dejarlo justo cuando empiece a funcionar.', null, 'proceso'),
  ('No hace falta que sea para siempre. Solo que sea hoy.', null, 'hoy'),
  ('Tu racha no te define. Lo que haces cuando se rompe, un poco más.', null, 'recaida'),
  ('Estás aprendiendo a estar contigo sin eso. Toma tiempo.', null, 'sentido'),
  ('Hoy también cuenta, aunque nadie te aplauda.', null, 'racha');
